### ISSUE TITLE
Request: handle blank artist field more gracefully

### ISSUE THREAD

**Issue by matijaerceg** [dlrudie/Snip#480] opened 2021-11-16 21:46 UTC
Spotify supports local files. Sometimes the metadata of those files is imperfect, such as when the artist and song name are both in the song name, or an artist name is just missing. When this happens, Snip currently sends the variable name to the output .txt like so:

![image](https://user-images.githubusercontent.com/4306199/142070870-ab07f506-7bdf-4ca5-976d-ae1c21e50e6e.png)

Instead, it would be great it it replaced the $$a with 'Unknown' or simply removed the separator and the artist name altogether.

**Comment by matijaerceg** [comment] 2021-11-16 21:47
Furthermore, when an artist name is missing in Spotify, and Snip is set to 'Save Information Separately', it doesn't even update the artist txt, but ideally it would blank it out at the same time that it updates the song txt.

**Comment by dlrudie** [comment] 2022-02-12 16:31
To this day I still haven't really experimented with local files (mainly because 100% of the music I listen to is already on Spotify or iTunes so I've never needed to keep any files locally). I will try to get around to it but given my current work it may be some time.

**Comment by dlrudie** [comment] 2022-02-12 17:03
Thanks. I'm just in a spot where I'm limited in time, in the middle of a redesign/rewrite of Snip, and still trying to support the current Snip as well.

I just need a free weekend of inspiration. :)

**Comment by dlrudie** [comment] 2022-10-07 23:12
Duplicate of #433. Soon.

**Closed by dlrudie** 2022-10-07 23:12 UTC
