### ISSUE TITLE
Spotify is not currently running

### ISSUE THREAD

**Issue by hakmeister** [dlrudie/Snip#318] opened 2018-08-10 07:14 UTC
6.10.0 and 6.10.2 seem to not see Spotify anymore. I'm running the standalone version not the windows store version. tried running snip in Administrator mode, numerous restarts and it is still not detecting.

**Comment by MeikelLP** [comment] 2018-08-10 07:59
duplicate of #315

**Closed** 2019-07-14 17:25 UTC
