### ISSUE TITLE
Snip stops detecting songs / song changes

### ISSUE THREAD

**Issue by Jreyno40** [dlrudie/Snip#390] opened 2019-09-08 03:14 UTC
Hi all, I can get snip to work for the first song or two (spotify, windows 10). However, it just stops working for whatever reason. Based on another issue I've ensured I'm only minimizing with the - sign or not minimizing spotify at all. I really don't know what's going on..

**Comment by jarentrux** [comment] 2019-09-08 22:15
If you are having localhost error then;

right click snip
select itunes
select spotify back

done :)

**Comment by dlrudie** [comment] 2019-09-15 08:02
Duplicate of #378.

**Closed by dlrudie** 2019-09-15 08:02 UTC

**Comment by Jreyno40** [comment] 2019-09-15 16:00
This definitely isn’t that problem you referenced. It isn’t a local host error, and I’m not clicking the x on Spotify. It’s something different than both of those things @dlrudie

**Comment by Jreyno40** [comment] 2019-11-07 17:08
If you ever swing back to this @dlrudie let me know! I'd be glad to help try and figure out the problem.
