### ISSUE TITLE
iTunes support removed?

### ISSUE THREAD

**Issue by Lethann** [dlrudie/Snip#453] opened 2021-02-21 14:43 UTC
When I run snip it automatically opens a browser window to spotify. Trying to right click the icon in the task bar does nothing. Is it now a spotify only program? Also the only way to exit is to use the Task Manager to end task.

**Comment by GenesisFR** [comment] 2021-02-22 00:24
It does support iTunes, however @dlrudie's logic when making v7 was flawed since it assumes everyone is gonna authenticate through Spotify. You have to get past that authentication window to be able to use Snip.

**Comment by dlrudie** [comment] 2021-04-08 22:10
I wouldn’t say so much that it was flawed. Just that there really wasn’t any other solution without more research.

The problem is that Spotify forces the authentication browser window. The other problem is that if iTunes is the default as soon as Snip launches and loads the library for iTunes the library itself will force iTunes to open automatically. So it was either have a browser window open or iTunes open.

I really need to revisit this and come up with a better solution. There’s been enough time online with all of the Spotify API changes that other people have probably come up with some good solutions too.

**Comment by GenesisFR** [comment] 2021-04-09 04:15
Oh ok, makes sense then.

**Comment by beeradmoore** [comment] 2021-05-07 00:50
Just came across this issue. I don't use Spotify and as such I can't use Snip without creating a throwaway account. 

Unless I am missing something about the auth flow above, It would be nice if on first launch it could detect if Spotify or iTunes is running and then default to that (start browser auth flow if Spotify is detected). If neither or both are detected then prompt a small UI window that asks you to setup for Spotify or for iTunes.

**Comment by dlrudie** [comment] 2022-10-07 23:01
I may revisit this soon. Maybe I can get by by just having the first entry just be a dummy entry, and then you can manually select which player you'd like from there.

**Comment by dlrudie** [comment] 2022-10-09 03:02
Fixed with cd419788b43b5c62512f4c29d9641b7ae8af92c2

**Closed by dlrudie** 2022-10-09 03:02 UTC
Labels: enhancement
