### ISSUE TITLE
Snip 5.3.1 needs an app to open and I by mistake set it to open with internet explorer 

### ISSUE THREAD

**Issue by Saluichi** [dlrudie/Snip#97] opened 2016-04-12 00:20 UTC
How do to fix the initial issue as well as undoing my screw up??

**Comment by dlrudie** [comment] 2016-04-13 01:22
Duplicate of #95.

When you install 7-Zip it can re-associate files for you.

**Closed by dlrudie** 2016-04-13 01:22 UTC

**Comment by Saluichi** [comment] 2016-04-13 02:13
so when I re associate files do I just run the ico as an application? do I just run it as an admin and it will run as normal??
