### ISSUE TITLE
Snip displays [foobar2000] in text file

### ISSUE THREAD

**Issue by AnarchinOfficial** [dlrudie/Snip#361] opened 2019-06-02 05:30 UTC
Is there a workaround to get rid of the [foobar2000] at the end of the text file?

**Comment by GenesisFR** [comment] 2019-06-02 06:12
Duplicate of #337. No workaround yet as no new build has been released.

**Comment by dlrudie** [comment] 2019-07-14 17:18
Foobar support is being dropped.

**Closed by dlrudie** 2019-07-14 17:18 UTC
