### ISSUE TITLE
Snip not working correctly with ITunes 

### ISSUE THREAD

**Issue by WolfManKing** [dlrudie/Snip#236] opened 2017-12-26 14:17 UTC
I'm a beginning streamer putting music from itunes onto my steam, but when i open Itunes through snip i get this error message
![capture](https://user-images.githubusercontent.com/34862214/34358401-1bc9c996-ea9b-11e7-8a7d-eda57bb2647a.JPG)
All of the music has been downloaded through apple music, but i get this message when itunes starts up through Snip.

**Comment by markspolakovs** [comment] 2017-12-26 15:02
Duplicate of #202.

**Comment by dlrudie** [comment] 2017-12-27 01:14
Duplicate #202

**Closed by dlrudie** 2017-12-27 01:14 UTC
