### ISSUE TITLE
iTunes error - "Error HRESULT E_FAIL has been returned from a call to a COM component"

### ISSUE THREAD

**Issue by MiaNeko** [dlrudie/Snip#221] opened 2017-11-07 16:57 UTC
Hi,

iTunes has recently had an update and now snip is not working with it. I tried redownloading snip but it has come up with the same error. Screenshot below.

![image](https://user-images.githubusercontent.com/33461465/32506407-6356ba02-c3dc-11e7-9e8a-2bf6c3df0cb1.png)

Thank you for your work with Snip. Please could you fix this when possible <3

**Comment by markspolakovs** [comment] 2017-11-07 19:35
Duplicate of #202.

**Closed** 2017-11-08 01:33 UTC
