### ISSUE TITLE
right click

### ISSUE THREAD

**Issue by vertex101** [dlrudie/Snip#381] opened 2019-08-03 07:44 UTC
I am using Win10 and with the latest version when i try to right click the icon in my tray it doesn't bring up no menu to change from spotify to itunes

**Comment by tombets2424** [comment] 2019-08-03 10:50
Yep, I had that. It forces you to log in to Spotify otherwise you can't right click to bring up snip's functions.

**Comment by murko69** [comment] 2019-08-03 10:58
I think #369 is the same and it's on the bug list

**Comment by vertex101** [comment] 2019-08-04 03:53
Ah okay I will give that a try and see if it will work for me

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dlrudie** [comment] 2019-09-15 07:59
Duplicate of #369 basically. It's still on my list.

**Closed by dlrudie** 2019-09-15 07:59 UTC
