### ISSUE TITLE
is no longer compatible

### ISSUE THREAD

**Issue by fenixreturn** [dlrudie/Snip#28] opened 2015-03-13 11:49 UTC
Snip is no longer compatible with the new spotify

**Comment by TrollWarlord** [comment] 2015-03-15 01:09
It's caused by the title not being in the right format now. I can't actually test / recompile since this was built for Windows only (No mono support).

**Comment by dlrudie** [comment] 2015-03-15 01:12
Duplicate of #26.

**Closed by dlrudie** 2015-03-15 01:12 UTC
