### ISSUE TITLE
Hotkey Issue when starting snip

### ISSUE THREAD

**Issue by fadderg** [dlrudie/Snip#309] opened 2018-07-23 06:30 UTC
Hey dlrudie, 
This is a similar problem to another post, but i still cant figure this out. 
Every time i want to start Up snip, this message along with many other pops Up: This hotkey is already registered by another application and will be skipped: Alt, Control, M. 

Is there any fix for this? It wont start because of my hotkeys somehow already are registred to something i dont know.

**Comment by fadderg** [comment] 2018-07-23 06:45
I want to mention that i first installed streamlabs chatbox, to run with my Spotify. But then i heard about snip, and wanted to try that instead. I uninstalled the chatbox app thinking that it could be the proplem, but it still doesnt Work.

**Comment by MeikelLP** [comment] 2018-07-23 09:37
I had the exact same message as you do. I think it's an actual bug.
But this bug **did not** stop me from working with Snip...

**Comment by fadderg** [comment] 2018-07-23 09:40
So it might Work even though i get this message every time i open it?

**Comment by MeikelLP** [comment] 2018-07-23 09:45
I think so, but currently I can't confirm it as I am not at home.

**Comment by GenesisFR** [comment] 2018-07-23 19:52
It means another program previously registered a global hotkey (aka keyboard shortcut) that Snip also wants to use. There's no reason why it'd prevent Snip from working.

You can just disable hotkeys if you don't use them, the warning should no longer appear.

![image](https://user-images.githubusercontent.com/3614449/43099371-fd482abe-8e8f-11e8-93d5-f505b9879d06.png)

Or you can try finding the program that is using this hotkey (nobody can help you do that, keep closing programs until the warning doesn't show up anymore).

**Comment by fadderg** [comment] 2018-07-23 20:14
Thanks for the response! Do you right click on snap to get the "Enable Hotkeys" settings to show?

**Comment by fadderg** [comment] 2018-07-23 20:30
I want to thank the guys who helped me here! I was blinded by the error messages, that i actually thought the program wasnt working.. But i works out fine for me! 
You guys rock!!

**Closed** 2018-07-23 23:13 UTC

**Comment by idk** [comment] 2018-07-29 23:15
Everyone who runs a NVIDIA GPU and has installed Geforce Experience gets this error as `ALT + CTRL + m` is the default Keybind for toggling Microphone on/off in record/broadcast/replay/shadowplay.

Myself the main reason I use Snip is for the Global Hotkeys option so disabling it is not feasible, the workaround I use is changing the keybind in Geforce Experience (until Snip fixes this bug/conflict).

**Comment by GenesisFR** [comment] 2018-07-30 02:06
Snip is using [global hotkeys](https://docs.microsoft.com/en-us/windows/desktop/inputdev/about-keyboard-input#hot-key-support) since it doesn't have a window. I think it's the only way to have working keyboard shortcuts without having focus on your application.

The problem is that any other application that registered global hotkeys before Snip was launched will have precedence over Snip, so the only way to circumvent this is to either change the hotkeys in other applications or have custom hotkey support in Snip (it seems to be [planned](https://github.com/dlrudie/Snip/blob/master/Snip/KeyboardHook.cs#L92) at some point),
