### ISSUE TITLE
Spotify not working

### ISSUE THREAD

**Issue by mjgj96** [dlrudie/Snip#299] opened 2018-07-19 14:19 UTC
I noticed that the Spotify source for Snip was really buggy, but somehow in the middle of using it, Snip had stopped working entirely, only saying "No Track Playing" or "Spotify is not currently running". I tried running the source code in Visual Studios, but noticed this in the output:

C:\Users\User\Desktop\Snip-6.9.5\Snip\Players\Spotify.cs(534,129,534,144): error CS0103: The name 'ApplicationKeys' does not exist in the current context

Followed by an error saying "The name 'ApplicationKeys' does not exist in the current context"

Did you maybe forget to put the file back when you pushed to GitHub? Still not sure how it was working before without that file, but I hadn't changed any settings in Spotify or Snip while using it and I noticed it went from showing the song playing to saying "No Track Playing". I haven't gone into depth with your project here so I don't understand these errors entirely, let alone their dependencies.

**Comment by eav86** [comment] 2018-07-19 14:24
Same here. Snip has stopped working with catching Song from spotify. While i havent change a thing. It still works with VLC. But not Spotify

**Comment by MeikelLP** [comment] 2018-07-19 17:00
Probably Spotify has changed a thing. Spotify does this often and has no public api which causes inconsitence.

**Comment by Florenzius** [comment] 2018-07-19 17:39
Please fix that! I can't get it working...

**Comment by Vindexus** [comment] 2018-07-19 17:40
I'm running into this issue as well.

**Comment by markspolakovs** [comment] 2018-07-19 17:45
`ApplicationKeys` is intentionally ignored:

https://github.com/dlrudie/Snip/blob/dfda32e26e6b2a4621c2d3734727877a6818c09e/.gitignore#L116

This is because it contains DLRudie's private Spotify API key. If you want to add your own, first [register an app](https://developer.spotify.com/dashboard/applications) in Spotify's dashboard, then use the [Client Credentials flow](https://developer.spotify.com/documentation/general/guides/authorization-guide/#client-credentials-flow) to get the key you need (TL;DR get your client ID and secret, concatenate them with a colon (`client_id:client_secret`), base64 encode that, then post it like so: `curl -X "POST" -H "Authorization: Basic YOUR_BASE64_HERE" -d grant_type=client_credentials https://accounts.spotify.com/api/token`). Then, create ApplicationKeys.cs yourself like so:

```cs
namespace Winter {
  internal sealed class ApplicationKeys {
    internal const string Spotify = "YOUR_KEY_HERE";
  }
}
```

(i hope)

**Comment by MeikelLP** [comment] 2018-07-19 18:09
Why isn't this configurable?

**Comment by Vierdz** [comment] 2018-07-19 18:13
I've had this problem on and off in the past, usually it resolves itself somehow but now it's flat out not working.

**Comment by markspolakovs** [comment] 2018-07-19 18:14
@Vierdz if you're talking about `"No Track Playing" or "Spotify is not currently running"`, that's not what we're discussing here, comment in any of the other issues about that, I guarantee adding a Spotify key won't resolve it

**Comment by Vierdz** [comment] 2018-07-19 18:16
Thanks!

**Comment by Florenzius** [comment] 2018-07-19 19:05
@markspolakovs The first post is also about the error and his guess why it appears. So I have no idea when this will be fixed.. In fact it's keeping me away from streaming and it's annoying

**Comment by markspolakovs** [comment] 2018-07-20 07:17
@Florenzius (and everyone else, for reference): when DLRudie builds the Snip that you download (in the 7z file) on his computer, he includes his key, so the problem isn't there. It's only when he pushes the code to GitHub that he removes it, to prevent abuse.

**Comment by mjgj96** [comment] 2018-07-20 15:33
Oh no...I think Spotify may have changed too drastically for a quick fix to Snip: "Remote control of Spotify’s desktop app has been deprecated in favour of full track playback in the browser." -[_New Updates to Spotify Play Button_](https://developer.spotify.com/community/news/2018/07/19/new-updates-to-spotify-play-button/), Spotify AB, July 19th

**Comment by hakmeister** [comment] 2018-07-20 20:19
When I get home I’m going to try to revert the Spotify update. I don’t know if this is fixable anytime soon.

**Comment by markspolakovs** [comment] 2018-07-20 20:21
I suppose it _could_ be ported to use https://developer.spotify.com/documentation/web-api/reference/player/... would require users to sign in, which would be a pain in the ass but not impossible

**Comment by dlrudie** [comment] 2018-07-21 03:55
Ugh.

**Comment by dlrudie** [comment] 2018-07-21 03:56
I'll figure this out one way or another.

**Comment by dlrudie** [comment] 2018-07-21 04:00
So I have a plan. Those of you that have your compile environments set up I'll be pushing something tonight hopefully.

**Comment by hakmeister** [comment] 2018-07-21 04:03
I honestly thought reverting Spotify versions would’ve fixed this? Tried 6.9.5 and 6.9.1

**Comment by dlrudie** [comment] 2018-07-21 04:54
No. Spotify disabled their local API endpoint for controlling the desktop app.

**Comment by dlrudie** [comment] 2018-07-21 06:35
I had to go the hacky route and open the process to read memory. I found a static address in memory that contains the track ID so I can use that. HOWEVER, this address will HIGHLY LIKELY change with each new version of Spotify. I'll need to implement a function in the future to automatically figure out the memory address.

**Comment by markspolakovs** [comment] 2018-07-21 07:39
@dlrudie there exists this web API endpoint: https://developer.spotify.com/documentation/web-api/reference/player/get-the-users-currently-playing-track/ - it seems to be the "official" way of doing this. However, it requires the user to sign in with their Spotify account, which would require opening their OAuth flow in a WebView, This seems like the best way of doing this in the long term, but it would require rewriting much of the Spotify code.

**Comment by dlrudie** [comment] 2018-07-21 07:41
I've already rewrote the majority of the Spotify code tonight. What I have going works great. But only once it's out there will I know if it works for everyone or not. It should be the most reliable solution yet.

**Closed** 2018-07-21 08:58 UTC

**Comment by MeikelLP** [comment] 2018-07-21 09:17
Too bad I just started implementing https://github.com/JohnnyCrazy/SpotifyAPI-NET/ into the app so it is more future proofed ._.
Guess I stop that :D

**Comment by roachadam** [comment] 2018-07-24 04:51
Easiest solution here is to just read the artist/song from the spotify title window.

**Comment by ClutchKey** [comment] 2018-07-24 06:03
So when I downloaded Snip, it doesn't have like a n application button. I downloaded it during 6.9.1, and it had that button. I don't know what to do after downloading it now.

**Comment by MeikelLP** [comment] 2018-07-24 06:56
@ClutchKey be sure to check your tray popup. Windows might hide it behind other tray icons. If not please verify that the process is running via task manager

**Comment by ClutchKey** [comment] 2018-07-24 06:59
Wait @MeikelLP how exactly do I do that?

**Comment by MeikelLP** [comment] 2018-07-24 07:22
like this: ![tray](https://cdn.ghacks.net/wp-content/uploads/2015/03/windows-10-system-tray.png)
It may hide there and you do not directly see it.

**Comment by ClutchKey** [comment] 2018-07-24 08:11
@MeikelLP Ok well it pops up, but it still says 6.9.1 for me

**Comment by GenesisFR** [comment] 2018-07-24 08:30
Well if it says 6.9.1 then you obviously don't have the latest version.

![image](https://user-images.githubusercontent.com/3614449/43126261-3771c55a-8efa-11e8-9011-8096a750e0e6.png)

**Comment by ClutchKey** [comment] 2018-07-24 08:50
@GenesisFR I realize that thank you. But when I downloaded it, it's not showing an application for me to use it...

**Comment by ClutchKey** [comment] 2018-07-24 09:06
No @GenesisFR I downloaded everything that came with the 6.10.1. My PROBLEM is that I don't see an application to run it. It's all the scripts and stuff, but there is no app to use it. It's still showing the old version of 6.9.1 for me. I see it in the task manager, but again, it says it is still running 6.9.1.

**Comment by MeikelLP** [comment] 2018-07-24 09:17
Did you download `Snip-v6.10.1.zip` or `Source code (zip)` ? Sounds like you downloaded the source code not the application.

**Comment by GenesisFR** [comment] 2018-07-24 09:21
If there's no executable inside `Snip-v6.10.1.zip`, you can blame your antivirus.

**Comment by ClutchKey** [comment] 2018-07-24 09:22
@MeikelLP Where would I find the snip 6.10.1 zip? I may have downloaded the source code zip by mistake

**Comment by ClutchKey** [comment] 2018-07-24 09:32
Thank you @MeikelLP !!!!! Much Appreciated

**Comment by tsuNammi** [comment] 2018-08-03 19:47
I had this problem, updated to 6.10.2 - then it worked. 

After a week now, suddenly it stops working. It can start from beginning of the stream, then suddenly, the Snip.txt file is empty - doesn't help if i close/reopen Spotify and/or Snip. Anyone still having issues?

**Comment by MeikelLP** [comment] 2018-08-03 20:16
@tsuNammi see #315
