### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by samhazza** [dlrudie/Snip#98] opened 2016-04-16 10:09 UTC
When I download snip it just downloads a 7Z file and wont let me open or run it, am I missing some software which will allow me to run it? I had it on my old pc but this is brand new that ive had for 2 days

**Comment by FyreFlyGJh** [comment] 2016-04-16 13:40
Same here, there is no zip folder with any files to download and extract for Snip. It's just downloading a blank document icon with nothing there but the Snip version name and numbers. I emailed the Snip creators last night, but so far no response yet. It seems that it's the same issue for all the Snip program downloads for every version on the site.

**Comment by dlrudie** [comment] 2016-04-16 14:52
Duplicate of #95

**Closed by dlrudie** 2016-04-16 14:52 UTC
